apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: abhinav332/multiplepostgres:latest
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: password
        - name: POSTGRES_MULTIPLE_DATABASES
          value: db1,db2,db3,db4
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-claim
